[project]
name = "sentinel"
version = "0.1.0"
description = "The backend for the Crown Point Consulting project."
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.0",
    "uvicorn>=0.39.0",
    "python-dotenv"
]
